version: 2.1
orbs:
  phpcs: vip_migration/phpcs@0.0.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - phpcs/install-phpcs
      - run:
          command: |
            phpcs
  unit_test:
    docker:
      - image: circleci/php:7.3-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - phpcs/install-phpunit
      - run:
          command: |
            phpunit --help
workflows:
  version: 2
  phpcs_phpunit:
    jobs:
      - build:
          filters:
            branches:
              only:
                - staging
                - develop
                - master
      - unit_test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - staging
                - develop

            

     
    
